// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package cn.mrcode.study.rpc.s06.grpc.hello;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
